<a href="https://colab.research.google.com/github/JoshKonoff/simple_ML_project/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#in this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow #control MM

More specifically, we're going to cover:
*Intro to tensors
* Getting info from tensors
*Manipulating tensors
*Tensors & Numpy
Using @tf.function (a way to accelerate your regular python functions
Using GPUs with TensorFlow (or TPUs)
*Exercises to try for yourself!

Introduction to Tensors

In [1]:
#Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

In [4]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
#Create a matrix (has more than 1 dimension)

matrix = tf.constant([[10,7],
                     [7,10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Create another matrix

another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9. ]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
tensor = tf.constant([[[1,2,3,],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                     [[13,14,15],
                      [16,17,18]]])

tensor


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

What we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and directon)
* Matrix: A 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (when n can be any number, a 0-dimensional is a scalar, a 1-dimensional tensor is a vector )

In [12]:
### Creating tensors with `tf.Variable`

In [13]:
# Create the same tensor with tf.Variable([10,7]) as we did above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
#how about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor   #this correctly updates the 10 to 7 in numpy array

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

# Creating random tensors

Random tensors are tensors of some abitrary size which contain random numbers.

In [15]:
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility (similar to numpys 'random_seed')
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3,2))

#Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

# Shuffle the order of elements in a tensor

In [16]:
#Shuffle a tensor (valuable for when you want to suffle your tensor so that the inherent order doesn't affect learning)
not_shuffled = tf.constant([[10, 7], #there are two elements in the shape attribute 10,7..3,4...2,5
                           [3,4],
                           [2,5]])
not_shuffled.ndim
2

2

In [17]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [18]:
#shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)   #shuffles across the 1st dimension

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [19]:
not_shuffled   #https://www.tensorflow.org/api_docs/python/tf/random/set_seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [20]:
#It looks like if we want our suffled tensors to be in the same order, we got to use the global level random seed as well as the operation level seed:

#Rule 4: If both the global and operation seed are set: Both seeds are used in conuction to determine the random sequence

In [21]:
tf.random.set_seed(42) #global level random seed
tf.random.shuffle(not_shuffled, seed=42) #operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

#other ways to make tensors

In [22]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [23]:
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

Turn Numpy arrays into tensors 
#The main difference btwn Numpy arrays and TensorFlow tensors is that tensors can run on GPU computing

In [24]:
#You can also turn Numpy arrays into tensors

import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32) #Create a Numpy array btwn 1 and 25
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [25]:
#How can we covert numpy_A into a tensor? Tensors can run on GPU and GPUs are much faster at finding numerical patterns
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [26]:
'''
A = tf.constant(numpy_A, shape=(2,3,4)) #must add up to 24 b/c we have 24 shape above. With 2,3,4 we are converting it into a 3D array (still needs to multiply into 24)
B = tf.constant(numpy_A)
A,B
'''

'\nA = tf.constant(numpy_A, shape=(2,3,4)) #must add up to 24 b/c we have 24 shape above. With 2,3,4 we are converting it into a 3D array (still needs to multiply into 24)\nB = tf.constant(numpy_A)\nA,B\n'

Getting info from tensors  

When dealing with tensors you probably want to be aware of the following attributes


*   Shape
*   Rank
*   Axis or dimension
*   Size




In [27]:
#Create a rank 4 tensor (rank stands for the number of dimensions - in this case 4 dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [29]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [30]:
2*3*4*5

120

In [31]:
#Get various attributes of our tensor
print('Datatype of every element:', rank_4_tensor.dtype)
  

Datatype of every element: <dtype: 'float32'>


In [32]:
#Tensors can be indexed just like Python lists
#So if you want to get the first 2 elements in each dimension you can write:

rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [33]:
some_list = [1, 2, 3, 4]
print(some_list[:-1]) 

[1, 2, 3]


In [34]:
#Get the elements from each dimension except for the final one
rank_4_tensor[:-1, :-1, :-1, :-1]

<tf.Tensor: shape=(1, 2, 3, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [35]:
#Get the first element from each dimension from each index except get the whole final one
rank_4_tensor[:1, :1, :1]   #You can simply leave off the final comma and it will get the whole element (5 in this case). Or you can do(:1, :1, :1, :)

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [36]:
rank_4_tensor[:1, :, :1, :1]   # : for an element (after a comma) tells python to get the whole element

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

Tensors can be indexed just like Python lists.

In [37]:
# Get the first 2 elements of each dimension (works in a tensor too)
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [38]:
rank_2_tensor = tf.constant([[10,7],
                            [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [39]:
# Get the last item of each of our rows for our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [40]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]   #...  = [:, :, t.f.newaxis]  ... means 'include those' and add a newaxis on the end
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [41]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1)  # '-1' means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [42]:
# Expand the 0-axis
tf.expand_dims(rank_2_tensor, axis=0)   #in this example our new axis will be on the front instead of the end


<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

# Manipulating tensors (tensor operations)

In [43]:
#Basic operations

#You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [44]:
#Notice that the original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [45]:
#You can change the original tensor with:
tensor = tensor + 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [46]:
#Multiplication, substraction, division also work

In [47]:
#We can use the tensorflor builtin function too
#tf.math

tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]], dtype=int32)>

In [48]:
tf.divide(tensor, 2)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[10. ,  8.5],
       [ 6.5,  7. ]])>

In [49]:
tf.subtract(tensor, 5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[15, 12],
       [ 8,  9]], dtype=int32)>

In [50]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [51]:
#The above basic operations are 'element wise' operations. That means that they go through one by one
#Ex. tf.add will go through one by one and add 10 to each element in the tensor

In [52]:
# matrix wise (aka tensor wise) can be visualized on mathisfun.com and matrixmultiplication.xyz


In machine learning, matrix multiplication is one of the most common tensor operations

In [53]:
# Matrix mutliplication in tensorflow
#Multiplies matrix a by matrix b, producing a * b
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]], dtype=int32)>

In [54]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[400, 289],
       [169, 196]], dtype=int32)>

In [55]:
#How to do matrix multiplication with Python operation '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]], dtype=int32)>

In [56]:
#the above example won't work if these tensors have different shapes.
#b/c we are doing tensor matmul tensor they have the same shape (in this case each is (2,2))

tensor.shape
#Remember that rows come first, then columns
#(3, 2) means 3 rows and 2 columns

TensorShape([2, 2])

In [57]:
# Create a tensor (3,2) tensor
x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
# Create another (3,2) tensor
y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

# Try to matrix multiply tensors of same shape
# x @ y  - doesn't work b/c there are two rules our tensors (or matrices need to fulfil if we're going to matrix multiply them:)
#1. The inner dimensions must match
#2. The resulting matrix has the shape of the outer dimensions

In [58]:
#https://www.khanacademy.org/math/precalculus/x9e81a4f98389efdf:matrices/x9e81a4f98389efdf:multiplying-matrices-by-matrices/v/matrix-multiplication-intro

In [59]:
#in the cell above we changed the shape so that now it has two rows and 3 columns

In [60]:
# Try to matrix multiply X by reshaped Y
x.shape, tf.reshape(y, shape=(2,3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [61]:
x @ tf.reshape(y, shape=(2,3))   #now it works b/c we have an inner dimension of 2 in both

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [62]:
tf.matmul(x, tf.reshape(y, shape=(2,3))) #same output as above

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [63]:
# Does it still work if we change the shape of x instead of y?
tf.matmul(tf.reshape(x, shape=(2,3)), y)  #yes it work but it gives us different results

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [64]:
# Can do the same with transpose   - the difference btwn transpose and reshape is that transpose flips the axises
tf.transpose(x), tf.reshape(x, shape=(2,3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [65]:
#Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(x), y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [66]:
# https://erik-engheim.medium.com/why-does-matrix-multiplication-work-the-way-it-does-7a8ed9739254#:~:text=This%20are%20just%20simple%20rules,find%20the%20dot%20product%20of.
# https://www.youtube.com/watch?v=2spTnAiQg4M

###   Great Apple Pie example of why to do it this way: https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [67]:
#The dot product

#Matrix multiplication is also referred to as the dot product.
#You can perform matrix multiplication using:
#tf.matmul()
#tf.tensordot()

In [68]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
# transposing is flipping the axis
# whereas reshaping is just reshuffling

In [69]:
x, y
#x is a tensor of shape 3 and 2
#y is also a tensor of shape 3 and 2

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [70]:
#Perform the dot product on x and y requires x or y to be transposed
tf.tensordot(tf.transpose(x), y, axes=1) #on the first axis

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [71]:
#Perform matrix multiplication btwn x and y (transposed)
tf.matmul(x, tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [72]:
# Perform matrix multiplication between x and y (reshaped)   #so we see we get different results from transpose to reshape
tf.matmul(x, tf.reshape(y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [73]:
# Check the values of Y, reshape Y and transposed Y

#This is how you can investigate silent errors

print('Normal Y: ')
print(y, '\n')  #'\n is for newline

print('Y reshaped to(2,3):')
print(tf.reshape(y, (2,3)), '\n')

print('Y transposed:')   #all we've done here is flip the axises
print(tf.transpose(y))

Normal Y: 
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to(2,3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [74]:
tf.matmul(x, tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

Generally, when performing matrix multiplication and one of the axes doesn't line up, you will transpose (rather than reshape) one of the tensors to satisfy the matrix multiplication rules

#the default data type of most data types is int32
#What if you want to change that

#Create a new tensor with default datatype(float32)

In [75]:
B=tf.constant([17, 7.4])
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([17. ,  7.4], dtype=float32)>,
 tf.float32)

In [76]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [77]:
# Change from float32 to float16
# if we want to run our operations faster, we can run them on 16 (instead of 32 bit precision)
#How might we change 'C' above to 16?

D = tf.cast(B, dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([17. ,  7.4], dtype=float16)>

In [78]:
# Change from int32 to float32
E = tf.cast(D, dtype=tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([17.       ,  7.3984375], dtype=float32)>,
 tf.float32)

In [79]:
# Aggregating tensors
# Aggregating tensors = taking a large number of values and concentrating them down

In [80]:
# Get the absolute values
D = tf.constant([-7, -10]) #create a new tensor
D


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [81]:
# Get the absolute values
tf.abs(D)   #absolute values = take the negative numbers and gives the positive numbers

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [82]:
#Let's go through the following forms of aggregation:
#Get the min
#Get the max
#Get the mean of a tensor
#Get the sum of a tensor

In [83]:
# Create a random tensor with values between 0 and 1000 of size 50
E = tf.constant(np.random.randint(0,100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([87, 99, 98, 62, 72, 76, 76, 79, 76,  2, 96, 64, 86, 33, 14,  3, 20,
       89,  0, 69, 84, 90, 88, 77, 61, 47,  4, 31, 81, 65, 44, 67, 64, 32,
       16, 38, 26, 27, 81, 62, 59, 68, 16, 46,  4, 18,  3, 77, 41, 90])>

In [84]:
tf.size(E), E.shape, E.ndim
#find the min
tf.reduce_min(E)
np.min(E)

0

In [85]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [86]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=54>

In [87]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2708>

Excerise: Find the variarance and standard deviation of our E tensor using TensorFlow methods

In [88]:
# To find the variance of our tensor, we need access to tensorflow probability
import tensorflow_probability as tfp

In [89]:
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=922>

In [90]:
#Find the standard deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float32)) #has to be a float to get the std so cast it as a float 

<tf.Tensor: shape=(), dtype=float32, numpy=30.366667>

In [91]:
#tf.math.reduce_std(E)
#if you get the type error 'input must be real or complex'
#Go to the reduce_std docs
#and you'll notice the example: x = tf.constant([[1., 2.], [3., 4.]])
# https://www.tensorflow.org/api_docs/python/tf/math/reduce_std

In [92]:
 #This also works:
 #tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))
 #We didn't need access to tensorflow probability

Find the postional maximum and minimum

In [93]:
#at what row in the tensor does the max and min appear?

In [94]:
# Create a new tensor for finding positional min and max
#tf.random.set_seed(42)
F = tf.random.uniform(shape=[50]) #Create a tensor with 50 random numbers to work with
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [95]:
# Find the positional maximum
tf.argmax(F)    #similar with numpy. numpy.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [96]:
#Index on our largest value position. Very cool!
F[tf.argmax(F)]


<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [97]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [98]:
# Check for equality just to be safe
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [99]:
# Find the positional minimum
tf.argmin(F)


<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [100]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [101]:
F[tf.argmin(F)] == tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [102]:
#Sqeezing a tensor(removing all single dimensions)

In [103]:
# Create a tensor to get started
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50) )
G
#The shape is what we have want to pay attention to with squeezing

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [104]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [105]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape
#Removes dimensions of size 1 from the shape of the tensor


(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
        0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
        0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
        0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
        0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
        0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
        0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
        0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
        0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
        0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
       dtype=float32)>, TensorShape([50]))

In [106]:
# What is One-Hot encoding

In [107]:
# Create a list of indices
some_list = [0,1,2,3] #could be red,green,blue, purple

#One hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

Squaring, log, square root

In [108]:
# New way to create a new tensor

H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [109]:
# Find the square root
#tf.sqrt(H)  doesn't work - tells us to that it needs to be float, so...
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [110]:
# Find the log
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [111]:
### Tensors and NumPy

# Create a tensor directly from a Numpy array
# Numpy and Tensorflow have full interoperability - They work together real nicely
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [112]:
# Convert our tensor back to a NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [113]:
# Convert tensor J to a NumPy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [114]:
J = tf.constant([3.])
J.numpy()

array([3.], dtype=float32)

In [115]:
J.numpy()[0]

3.0

In [116]:
#If there's something that doesn't work in tensors or numpy then we can covert to the other

In [117]:
# The default types of each are slightly different

numpy_J = tf.constant(np.array([3., 7., 10.]))   #creating a tensor from a numpy array
tensor_J = tf.constant([3., 7., 10.])            #creating a tensor from a python list

numpy_J.dtype, tensor_J.dtype
#you will often run into issues due to these different data types. You can solve it by casting

(tf.float64, tf.float32)

In [118]:
# Example of regression problems    - predicting a number of some sort
#How much will this house sell for?
#How many people will buy this app?
#How much will my health insurance be?
#How much should I save each week for fuel?

In [119]:
#The dependent variable is the outcome variable - ex: the price of the house - the outcome we're trying to predict
#Independent variables - predictors - features - ex: how many rooms we have in the house, the number of bathrooms...Both combined